name: randevu_sistemi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Ek paketler burada tanımlanmalı
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wpLogo.png
    - assets/images/depositphotos_392760248-stock-photo-green-grass-texture-sport-background.jpg


