// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1rs1v5hEHUDfqcfFV8FA7dwblPZbclzg',
    appId: '1:811741449979:web:5b35908bd2f11ba7c12a5e',
    messagingSenderId: '811741449979',
    projectId: 'halisahaproje-75fcb',
    authDomain: 'halisahaproje-75fcb.firebaseapp.com',
    storageBucket: 'halisahaproje-75fcb.firebasestorage.app',
    measurementId: 'G-KW5GQPS8DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXSp_FnDWD11smMfOKoAkSSOUDjiaNkiw',
    appId: '1:811741449979:android:c1296e078c03fc4fc12a5e',
    messagingSenderId: '811741449979',
    projectId: 'halisahaproje-75fcb',
    storageBucket: 'halisahaproje-75fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJ_tCS5Qplm-YahtL-q6RuXrLZ1cdr-k',
    appId: '1:811741449979:ios:6f35fc0bef6fce8ec12a5e',
    messagingSenderId: '811741449979',
    projectId: 'halisahaproje-75fcb',
    storageBucket: 'halisahaproje-75fcb.firebasestorage.app',
    iosBundleId: 'com.example.randevuSistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJ_tCS5Qplm-YahtL-q6RuXrLZ1cdr-k',
    appId: '1:811741449979:ios:6f35fc0bef6fce8ec12a5e',
    messagingSenderId: '811741449979',
    projectId: 'halisahaproje-75fcb',
    storageBucket: 'halisahaproje-75fcb.firebasestorage.app',
    iosBundleId: 'com.example.randevuSistemi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1rs1v5hEHUDfqcfFV8FA7dwblPZbclzg',
    appId: '1:811741449979:web:d7081c895651551fc12a5e',
    messagingSenderId: '811741449979',
    projectId: 'halisahaproje-75fcb',
    authDomain: 'halisahaproje-75fcb.firebaseapp.com',
    storageBucket: 'halisahaproje-75fcb.firebasestorage.app',
    measurementId: 'G-KRQNMF0KFE',
  );
}
